language: node_js
node_js:
- 10
before_deploy:
- echo $deploy_rsa_password | gpg --passphrase-fd 0 deploy_rsa.gpg
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_rsa
- ssh-add ./deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: yarn build && yarn export && yarn deploy
  on:
    branch: master
