language: node_js
node_js:
  - 10

before_deploy:
  - openssl aes-256-cbc -K $encrypted_22fb59dc8bfe_key -iv $encrypted_22fb59dc8bfe_iv -in .travis/deploy_key.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key

deploy:
  provider: script
  skip_cleanup: true
  script: yarn build && yarn export && yarn deploy
  on:
    branch: master
