language: node_js
node_js:
- 10
before_deploy:
- openssl aes-256-cbc -K $encrypted_22fb59dc8bfe_key -iv $encrypted_22fb59dc8bfe_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: yarn build && yarn export && yarn deploy
  on:
    branch: master
env:
  global:
    secure: S+J3DjxNCWkMOHYjVrdHJtvZ5TFKX8+as3VFMl9mJFEMtnj1kKTmJZ9LBa5bRoWzO8Fv7JLUwQ6+RKI7JPitjt9UqtOlzkyxPg72DdmJTpc1S12CEUaTGaMO3oFgEcW2ygTIAcvVDqiz5U7fg3EPc6CRe4/pHReRr7j5R5k7c7ov3Ld5hLIRFGzmHjpUuJp848ykq+opG87GNz7nLNBbcGPgW30+A/egC/BLuIIm7b8YVVyacz7kbh5OaKbpyJPSagdfFJKyL4vtE2k042p6opbjifKIHY9sIEYxnFf+XDYtYBoZOfWXBDa/UB1PH8Iaq2aGwM4IIiBiklyKb3qmaYiBSxwaArTnBKBNi1dYqlGy5Gtd493bpBcS8pAdQ3VeKYT+cvt5/AwfjmQp2wXIIgS9NE1kMvl8UjzmtVPPw9P+soGttoIrAKIr05vFr+5B7bv4Jm3dUJ3+kMoPOZLaHsR879mH2m53kiMgfbR2j3fz54knUHaay9RvXM4l9NQ7isxDbpqHz7XnL3khMErQpMT3OhcApo0hBKydVc3XJUJY+4a23JXGNdrwNUO8t6b5Y6rLiAIi4lJK22o6Q4Ua+9atavN+zXqF8a4TzyiLwFrxaxlWsbNneQVdTxDh0kNJN6JjgtdPMTh9cYRyqd7cQL+56yv8WfJ2r0h+hjuDpIA=
