language: node_js
node_js:
- 10
before_deploy:
- echo $deploy_rsa_password | gpg --passphase-fd 0 deploy_rsa.gpg
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_rsa
- ssh-add ./deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: yarn build && yarn export && yarn deploy
  on:
    branch: master
env:
  global:
  - secure: S+J3DjxNCWkMOHYjVrdHJtvZ5TFKX8+as3VFMl9mJFEMtnj1kKTmJZ9LBa5bRoWzO8Fv7JLUwQ6+RKI7JPitjt9UqtOlzkyxPg72DdmJTpc1S12CEUaTGaMO3oFgEcW2ygTIAcvVDqiz5U7fg3EPc6CRe4/pHReRr7j5R5k7c7ov3Ld5hLIRFGzmHjpUuJp848ykq+opG87GNz7nLNBbcGPgW30+A/egC/BLuIIm7b8YVVyacz7kbh5OaKbpyJPSagdfFJKyL4vtE2k042p6opbjifKIHY9sIEYxnFf+XDYtYBoZOfWXBDa/UB1PH8Iaq2aGwM4IIiBiklyKb3qmaYiBSxwaArTnBKBNi1dYqlGy5Gtd493bpBcS8pAdQ3VeKYT+cvt5/AwfjmQp2wXIIgS9NE1kMvl8UjzmtVPPw9P+soGttoIrAKIr05vFr+5B7bv4Jm3dUJ3+kMoPOZLaHsR879mH2m53kiMgfbR2j3fz54knUHaay9RvXM4l9NQ7isxDbpqHz7XnL3khMErQpMT3OhcApo0hBKydVc3XJUJY+4a23JXGNdrwNUO8t6b5Y6rLiAIi4lJK22o6Q4Ua+9atavN+zXqF8a4TzyiLwFrxaxlWsbNneQVdTxDh0kNJN6JjgtdPMTh9cYRyqd7cQL+56yv8WfJ2r0h+hjuDpIA=
  - secure: Ce2+1/pfJl2kvDDvA934h0N0UbTOdbY8BT5ro0gmV/kXcAwjfcKU36uJUfY72BSq/4srpTAP2w1oc/ifTOAde5p2cifDBc21VPFPho23/qPlxhEsC4MnCEsCQNAwCbeGbTbU8laIjiwkoUg/KAzYeFuGLZnH+HqmKdKG0njLXmELqc+jLZIBxBYxi0urzNvbg7PbxRIaN0I8ZvJmWVtD8ATDk220U1bqFB8emnDcuHQjd3iFuS+FRh00mwRWJjc3rSbNvPKRV+lokeWZZw/kpYpLB3ugJaWmCOQb6hrZmKLY4/GdMvd+wZSZ3Cto3+//RhwQiHKMTNEbeAl67u8/schqVgo+RP6ajR8vpvPjFz3DCGMfsMi8ausF/DxRf5GYkHeHuKx7WwLLPYo3nRWvAoTjRmp+0yYrXPjBesfl0wjBQ+HZzYis5uQu4CSza1TcVTZ2V1g4/Y7JfK2F8lRtHMmEUbkhq/MnOa3fV/+7k61LMBe2BLegvivUPnbZGkEZ2xrI/fWPQwq8TPVk1K1ivjawrM5kJiFhspZNOKJivIGxXbEFNx3ktWR5FsXJEwmxsYkJduv3mDF7Cj3DPbfVf66SRj15/937AzCC12WPU0sWlqlaiI+9K11IKsaPhCRMwzs9JcjG4bjKNMGtUjO2Iw8NVJLIHU12i8H7O8US+Tc=
