language: node_js
node_js:
- 10
env:
  global:
    secure: ZZ2LBfbF8HKD/P2QS3iXvz+F92KfcS8l8c/o76tWkGoCNPN/d4T5jxNJx5pUS7inMhTaQLPNIiR+jMF+KfqHsLJkymcTTSbZodNA6sRYBjn7s3t8xT7wcIwg/DnkO4Ev/5DjnCZ7Gq4iBc9pFHVsND0aRShD1W+HsvyXVfSc6/9vihWgVD+Mek4oVh6D+zc2f+5H3DS1cHArNYWnIWEfcDgVcBCbRjfFPocAuwK0FoII3ogfzqyEE5WOw4G1eYa3P/Z5jQcVTVNsv4P/iZN6rlSEunBNS1qr9G1Jfs7+FpcJqQzRQdKy4g51dI7Zapz+2Q/F1G17yycfolUFGJK18shfymPQmwrj230Jb/G+VAjBooxL4kTj8DDDSbk7kbd6iDjL+JL9FhMC8OommYM39I7Ex6nBTYqRog58DUs4LpZ49ifIF3RdtUjUB01mpmFIjKplXSeVsDIXl9ZLprcxt/ARLrcCWqZvG40BmveAARfOS+z+20S+qr79Px8UrvxFuonlfsqR4K2Iqhe4YiH3EjYrQsx2dUyxHuRD1o1YjKe+RsisbA7A9VZ4kFKtgRT9rZXZWEweN6uP+3C37jMPLRt20KH8uR6VVa50oue4TVI4d2Qcrlqz65mf6b+grzF1u74sK0TmFAtCkFMCOifgHTKTjb6Cabb7f+Q5D6BNUro=
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: yarn build && yarn export && yarn deploy
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_22fb59dc8bfe_key -iv $encrypted_22fb59dc8bfe_iv
  -in deploy_rsa.enc -out deploy_rsa -d
