language: node_js
node_js:
  - 10

before_deploy:
  - openssl aes-256-cbc -K $encrypted_c0846ac765aa_key -iv $encrypted_c0846ac765aa_iv -in .travis/deploy_key.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: yarn build && yarn export && yarn deploy
  on:
    branch: master
