version: 2

jobs:
    build:
        docker:
            - image: node:10
        steps:
            - run: apt-get update && apt-get -y install rsync
            - checkout
            - run: yarn install --frozen-lockfile
            - run: yarn build && yarn export
    deploy:
        machine:
            enabled: true
        steps:
            - run: rsync -e "ssh -o StrictHostKeyChecking=no" -ahv --delete ./out/* hoish.in:/var/www/hoish.in/

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
