version: 2
jobs:
    build:
        docker:
            - image: node:10
        steps:
            - run: apt-get update && apt-get -y install rsync
            - checkout
            - run: yarn install --frozen-lockfile
            - run: yarn build && yarn export
            - run: yarn deploy -e "ssh -o StrictHostKeyChecking=no"
