version: 2

jobs:
    build:
        docker:
            - image: node:10
        steps:
            - run: apt-get update && apt-get -y install rsync
            - checkout
            - run: yarn install --frozen-lockfile
            - run: yarn build && yarn export
    deploy:
        machine:
            enabled: true
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "e5:64:d1:e6:b3:4b:e8:ad:8e:2a:fd:40:c4:6f:a2:4a"
            - run: rsync -e "ssh -o StrictHostKeyChecking=no" -ahv --delete ./out/* hoish.in:/var/www/hoish.in/

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
