version: 2

jobs:
    build:
        docker:
            - image: node:10
        steps:
            - run: apt-get update && apt-get -y install rsync
            - checkout
            - run: yarn install --frozen-lockfile
            - run: yarn build && yarn export
            - persist_to_workspace:
                root: '.'
                paths:
                    - out
    deploy:
        machine:
            enabled: true
        steps:
            - attach_workspace:
                at: '.'
            - run: rsync -e "ssh -o StrictHostKeyChecking=no" -ahv --delete ./out/* ${DEPLOY_DEST}

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only:
                            - master
