version: 2
jobs:
    build:
        docker:
            - image: node:10
        steps:
            - checkout
            - run: yarn install --frozen-lockfile
            - run: yarn build && yarn export
    deploy:
        machine: true
        steps:
            - run: ls -al
            - run: rsync -ahv --delete ./out/* hoish.in:/var/www/hoish.in/
workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy
