version: 2
jobs:
    build:
        docker:
            - image: node:10
        steps:
            - checkout
            - run: yarn install --frozen-lockfile
            - run: yarn build && yarn export
            - persist_to_workspace:
                root: /tmp/workspace
                paths:
                    - out
    deploy:
        machine: true
        steps:
            - run: ls -al /tmp/workspace
            - run: rsync -ahv --delete /tmp/workspace/out/* hoish.in:/var/www/hoish.in/
workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
