name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            NODE_VERSION: '14'
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - uses: actions/cache@v2
              key: ${{ runner.os }}-${{ env.NODE_VERSION }}
              path: |
                ~/.yarn
                ./.next
                ./node_modules
            - run: yarn install --frozen-lockfile
            - run: yarn build
            - run: yarn export
            - uses: peaceiris/actions-gh-pages@v3
              if: github.ref == 'refs/heads/master'
              with:
                github_token: ${{ github.token }}
                publish_dir: ./out
